[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MCMCChainsStorage = "51a256e2-afd8-4c38-88d8-a98ba8ad53ca"
PairPlots = "43a3c2be-4208-490b-832a-a21dcd55d7da"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Tonari = "91081016-e225-4157-90a8-4c5abf36a564"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
